# Generated by Django 2.0.7 on 2018-07-24 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 24, 18, 56, 21, 946234)),
        ),
    ]
