# Generated by Django 2.0.6 on 2018-07-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='title',
        ),
    ]
